version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1003
      - TZ=Europe/London
    volumes:
      - ./jellyfin_config:/config
      - /media/storage/tvshows:/data/tvshows
      - /media/storage/movies:/data/movies
      - /media/storage/anime:/data/anime
      - /media/storage/music:/data/music
    ports:
      - 8096:8096
    restart: unless-stopped
